node_exporter_version: 1.6.0
node_exporter_arch: linux-amd64
node_exporter_service_template: node_exporter_service_v2.service
node_exporter_binary_dest: /usr/local/bin/node_exporter
node_exporter_service_source: templates/node_exporter_service_v2.service
node_exporter_service_dest: /etc/systemd/system/node_exporter.service